name: API testing

on:
  push:
    branches:
      - main

jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Make a directory to upload the test results
        run: mkdir -p testResults

      - name: Turn on the local server
        run: npm run tern-on-api &

      - name: Run postman collection
        run: newman run store.collection.json -r htmlextra --reporter-htmlextra-export testResults/index.html --reporter-htmlextra-darkTheme

      - name: Deploy the report
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: testResults
  
      - name: Update About section
        if: always()
        run: |
          curl -X PATCH \
          -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          -d '{"homepage": "https://gantz26.github.io/Task6-Postman", "description": "API testing results"}' \
          https://api.github.com/repos/${{ github.repository }}      